/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import {useEffect, useRef} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const GamingSetup = (props) => {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('/models/gaming_setup.glb')
    const { actions } = useAnimations(animations, group)
    console.log(actions)

    useEffect(() => {
        actions['Armature.002|mixamo.com|Layer0.001 Retarget'].play()
    }, []);

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group name="Armature" position={[2.521, 0, 0.024]} rotation={[0, -1.5, 0]} scale={3.533}>
                    <skinnedMesh
                        name="EyeLeft"
                        geometry={nodes.EyeLeft.geometry}
                        material={materials['Wolf3D_Eye.003']}
                        skeleton={nodes.EyeLeft.skeleton}
                        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
                        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
                    />
                    <skinnedMesh
                        name="EyeRight"
                        geometry={nodes.EyeRight.geometry}
                        material={materials['Wolf3D_Eye.003']}
                        skeleton={nodes.EyeRight.skeleton}
                        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
                        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
                    />
                    <skinnedMesh
                        name="Wolf3D_Body"
                        geometry={nodes.Wolf3D_Body.geometry}
                        material={materials['Wolf3D_Body.002']}
                        skeleton={nodes.Wolf3D_Body.skeleton}
                    />
                    <skinnedMesh
                        name="Wolf3D_Glasses"
                        geometry={nodes.Wolf3D_Glasses.geometry}
                        material={materials['Wolf3D_Glasses.002']}
                        skeleton={nodes.Wolf3D_Glasses.skeleton}
                    />
                    <skinnedMesh
                        name="Wolf3D_Hair"
                        geometry={nodes.Wolf3D_Hair.geometry}
                        material={materials['Wolf3D_Hair.002']}
                        skeleton={nodes.Wolf3D_Hair.skeleton}
                    />
                    <skinnedMesh
                        name="Wolf3D_Head"
                        geometry={nodes.Wolf3D_Head.geometry}
                        material={materials['Wolf3D_Skin.002']}
                        skeleton={nodes.Wolf3D_Head.skeleton}
                        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
                        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
                    />
                    <skinnedMesh
                        name="Wolf3D_Outfit_Bottom"
                        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
                        material={materials['Wolf3D_Outfit_Bottom.002']}
                        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
                    />
                    <skinnedMesh
                        name="Wolf3D_Outfit_Footwear"
                        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
                        material={materials['Wolf3D_Outfit_Footwear.002']}
                        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
                    />
                    <skinnedMesh
                        name="Wolf3D_Outfit_Top"
                        geometry={nodes.Wolf3D_Outfit_Top.geometry}
                        material={materials['Wolf3D_Outfit_Top.002']}
                        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
                    />
                    <skinnedMesh
                        name="Wolf3D_Teeth"
                        geometry={nodes.Wolf3D_Teeth.geometry}
                        material={materials['Wolf3D_Teeth.002']}
                        skeleton={nodes.Wolf3D_Teeth.skeleton}
                        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
                        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
                    />
                    <primitive object={nodes.Hips} />
                </group>
                <mesh
                    name="desk"
                    castShadow
                    receiveShadow
                    geometry={nodes.desk.geometry}
                    material={materials['Material.001']}
                    rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                    name="desk-stands"
                    castShadow
                    receiveShadow
                    geometry={nodes['desk-stands'].geometry}
                    material={materials['Material.002']}
                    rotation={[Math.PI / 2, 0, 0]}
                />
                <group
                    name="pc"
                    position={[-0.003, 2.671, -2.527]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.506}>
                    <mesh
                        name="Plane002"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane002.geometry}
                        material={materials['Material.003']}
                    />
                    <mesh
                        name="Plane002_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane002_1.geometry}
                        material={materials['Material.004']}
                    />
                    <mesh
                        name="Plane002_2"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane002_2.geometry}
                        material={materials['Material.005']}
                    />
                </group>
                <group
                    name="monitor-screen"
                    position={[-0.766, 2.587, -0.081]}
                    rotation={[Math.PI / 2, 0, 0.048]}
                    scale={1.552}>
                    <mesh
                        name="Cylinder_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder_1.geometry}
                        material={materials.plastic}
                    />
                    <mesh
                        name="Cylinder_2"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder_2.geometry}
                        material={materials.screen}
                    />
                </group>
                <mesh
                    name="monitor-stand"
                    castShadow
                    receiveShadow
                    geometry={nodes['monitor-stand'].geometry}
                    material={materials['Material.006']}
                    position={[-0.766, 2.587, -0.081]}
                    rotation={[Math.PI / 2, 0, 0.048]}
                    scale={1.552}
                />
                <mesh
                    name="keyboard"
                    castShadow
                    receiveShadow
                    geometry={nodes.keyboard.geometry}
                    material={materials['Material.007']}
                    position={[0.637, 2.599, 0.413]}
                    rotation={[Math.PI / 2, 0, -1.607]}
                    scale={0.782}
                />
                <mesh
                    name="mouse"
                    castShadow
                    receiveShadow
                    geometry={nodes.mouse.geometry}
                    material={materials['Material.008']}
                    position={[0.43, 2.609, -0.675]}
                    rotation={[Math.PI / 2, 0, -1.554]}
                    scale={0.204}
                />
                <mesh
                    name="mouse-pad"
                    castShadow
                    receiveShadow
                    geometry={nodes['mouse-pad'].geometry}
                    material={materials.Material}
                    position={[0.457, 2.595, 0]}
                    scale={[0.582, 1, 1.832]}
                />
                <group
                    name="chair"
                    position={[2.97, 0, 0.023]}
                    rotation={[Math.PI / 2, 0, 3.079]}
                    scale={0.82}>
                    <mesh
                        name="Cube_Cube001"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube_Cube001.geometry}
                        material={materials['Material.012']}
                    />
                    <mesh
                        name="Cube_Cube001_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube_Cube001_1.geometry}
                        material={materials['Material.013']}
                    />
                </group>
                <mesh
                    name="Cylinder"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder.geometry}
                    material={nodes.Cylinder.material}
                    position={[0, -0.124, 0]}
                    scale={[6.305, 0.045, 6.305]}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/gaming_setup.glb')

export default GamingSetup;