import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const HackerRoom = (props) => {
    const { nodes, materials } = useGLTF('/models/hacker-room.glb')
        return (
            <group {...props} dispose={null}>
                    <mesh
                        name="screen_screens_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.screen_screens_0.geometry}
                        material={materials.screens}
                    />
                    <mesh
                        name="screen_glass_glass_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.screen_glass_glass_0.geometry}
                        material={materials.glass}
                    />
                    <mesh
                        name="table_table_mat_0_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.table_table_mat_0_1.geometry}
                        material={materials.table_mat}
                    />
                    <mesh
                        name="table_table_mat_0_2"
                        castShadow
                        receiveShadow
                        geometry={nodes.table_table_mat_0_2.geometry}
                        material={materials.computer_mat}
                    />
                    <mesh
                        name="table_table_mat_0_3"
                        castShadow
                        receiveShadow
                        geometry={nodes.table_table_mat_0_3.geometry}
                        material={materials.server_mat}
                    />
                    <mesh
                        name="table_table_mat_0_4"
                        castShadow
                        receiveShadow
                        geometry={nodes.table_table_mat_0_4.geometry}
                        material={materials.vhsPlayer_mat}
                    />
                    <mesh
                        name="table_table_mat_0_5"
                        castShadow
                        receiveShadow
                        geometry={nodes.table_table_mat_0_5.geometry}
                        material={materials.stand_mat}
                    />
                    <mesh
                        name="table_table_mat_0_6"
                        castShadow
                        receiveShadow
                        geometry={nodes.table_table_mat_0_6.geometry}
                        material={materials.mat_mat}
                    />
                    <mesh
                        name="table_table_mat_0_7"
                        castShadow
                        receiveShadow
                        geometry={nodes.table_table_mat_0_7.geometry}
                        material={materials.arm_mat}
                    />
                    <mesh
                        name="table_table_mat_0_8"
                        castShadow
                        receiveShadow
                        geometry={nodes.table_table_mat_0_8.geometry}
                        material={materials.tv_mat}
                    />
                    <mesh
                        name="table_table_mat_0_9"
                        castShadow
                        receiveShadow
                        geometry={nodes.table_table_mat_0_9.geometry}
                        material={materials.cables_mat}
                    />
                    <mesh
                        name="table_table_mat_0_10"
                        castShadow
                        receiveShadow
                        geometry={nodes.table_table_mat_0_10.geometry}
                        material={materials.props_mat}
                    />
                    <mesh
                        name="table_table_mat_0_11"
                        castShadow
                        receiveShadow
                        geometry={nodes.table_table_mat_0_11.geometry}
                        material={materials.ground_mat}
                    />
                    <mesh
                        name="table_table_mat_0_12"
                        castShadow
                        receiveShadow
                        geometry={nodes.table_table_mat_0_12.geometry}
                        material={materials.key_mat}
                    />
            </group>
        )
}
useGLTF.preload('/models/hacker-room.glb')

export default HackerRoom;